services:
  php:
    image: php:8.3-fpm
    container_name: php
    volumes:
      - ./php:/var/www/html
    depends_on:
      - rust-server
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8090:80"
    volumes:
      - ./php:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  rust-server:
    build: ./rust-server
    container_name: rust-server
    ports:
      - "3003:3003"

  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: app
      POSTGRES_DB: appdb
    ports:
      - "5434:5432"
